REALMS: dict[str, list[str]] = {
  "Amnennar": ["EU", "FR"],
  "Angerforge": ["US", "EN"],
  "Arugal": ["US", "EN"],
  "Ashbringer": ["EU", "EN"],
  "Ashkandi": ["US", "EN"],
  "Atiesh": ["US", "EN"],
  "Auberdine": ["EU", "FR"],
  "Azuresong": ["US", "EN"],
  "Benediction": ["US", "EN"],
  "Bloodsail Buccaneers": ["US", "EN"],
  "Chromie": ["EU", "RU"],
  "Earthfury": ["US", "EN"],
  "Earthshaker": ["EU", "EN"],
  "Eranikus": ["US", "EN"],
  "Everlook": ["EU", "DE"],
  "Faerlina": ["US", "EN"],
  "Firemaw": ["EU", "EN"],
  "Flamegor": ["EU", "RU"],
  "Gehennas": ["EU", "EN"],
  "Giantstalker": ["EU", "EN"],
  "Golemagg": ["EU", "EN"],
  "Grobbulus": ["US", "EN"],
  "Hydraxian Waterlords": ["EU", "EN"],
  "Jin'do": ["EU", "EN"],
  "Lakeshire": ["EU", "DE"],
  "Maladath": ["US", "EN"],
  "Mandokir": ["EU", "ES"],
  "Mankrik": ["US", "EN"],
  "Mirage Raceway": ["EU", "EN"],
  "Mograine": ["EU", "EN"],
  "Myzrael": ["US", "EN"],
  "Nethergarde Keep": ["EU", "EN"],
  "Old Blanchy": ["US", "EN"],
  "Pagle": ["US", "EN"],
  "Patchwerk": ["EU", "DE"],
  "Pyrewood Village": ["EU", "EN"],
  "Razorfen": ["EU", "DE"],
  "Remulos": ["US", "EN"],
  "Skyfury": ["US", "EN"],
  "Sulfuras": ["US", "EN"],
  "Sulfuron": ["EU", "FR"],
  "Thekal": ["EU", "EN"],
  "Transcendence": ["EU", "DE"],
  "Venoxis": ["EU", "DE"],
  "Westfall": ["US", "EN"],
  "Whitemane": ["US", "EN"],
  "Windseeker": ["US", "EN"],
  "Yojamba": ["US", "EN"],
  "伊弗斯": ["TW", "ZH_TW"],
  "古雷曼格": ["TW", "ZH_TW"],
  "札里克": ["TW", "ZH_TW"],
  "烏蘇雷": ["TW", "ZH_TW"],
  "瑪拉頓": ["TW", "ZH_TW"],
  "逐風者": ["TW", "ZH_TW"],
  "阿拉希盆地": ["TW", "ZH_TW"],
  "魚人": ["TW", "ZH_TW"],
  "라그나로스": ["KR", "KO"],
  "로크홀라": ["KR", "KO"],
  "서리한": ["KR", "KO"],
  "소금 평원": ["KR", "KO"],
  "얼음피": ["KR", "KO"],
}

REGIONS = [
    "EU",
    "US",
    "KR",
    "TW",
    # "CN", # RIP
]
